---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: git-ci
      PROJECT_ID: manifest-frame-431615-j8
      GAR_LOCATION: asia-southeast1
      REPOSITORY: github-action
      SERVICE: python-app
      REGION: asia-southeast1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Build docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v patch

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/$PROJECT_ID/github-action/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/$PROJECT_ID/github-action/$IMAGE_NAME:$GIT_TAG
          docker push asia-southeast1-docker.pkg.dev/$PROJECT_ID/github-action/$IMAGE_NAME:latest
          docker push asia-southeast1-docker.pkg.dev/$PROJECT_ID/github-action/$IMAGE_NAME:$GIT_TAG

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: asia-southeast1-docker.pkg.dev/${{env.PROJECT_ID}}/github-action/${{env.IMAGE_NAME}}:latest

      - name: Use Output
        run: curl ${{ steps.deploy.outputs.url }}
